### ISSUE TITLE
Should we use .del or .ostw files?

### ISSUE THREAD

**Issue by AlexejheroYTB** [ItsDeltin/Overwatch-Script-To-Workshop#54] opened 2019-08-28 12:30 UTC

**Comment by AlexejheroYTB** [comment] 2019-08-28 19:06
VS Code displays errors in the Problems tab only if the file is .ostw. No
errors are actually displayed for .del files.

On Aug 28, 2019 at 9:29 PM, ItsDeltin <notifications@github.com> wrote:

It only matters for the vscode extension activation events, all of these
will work:
".del",
".ostw",
".workshop"

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/issues/54?email_source=notifications&email_token=AHV6XKGX4Q3BTKU4QYNF4E3QG27XZA5CNFSM4IRFLCX2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5MBRZI#issuecomment-525867237>,
or mute the thread

**Comment by TrueCP6** [comment] 2019-08-29 11:39
Errors are displaying correctly for me in .del files. Do you have the latest extension installed? If yes then this may be a duplicate of #15.

**Closed** 2019-09-03 03:26 UTC

**Comment by AlexejheroYTB** [comment] 2020-01-10 15:42
Now errors are reported in `.del` files but not in `.ostw` ones

**Comment by TrueCP6** [comment] 2020-01-10 15:48
This is because non .del files are broken right now (#93).
